### ISSUE TITLE
No real idempotence

### ISSUE THREAD

**Issue by rembik** [robertdebock/ansible-role-bootstrap#23]
**Describe the bug**
No real idempotence as described [here](https://github.com/robertdebock/ansible-role-bootstrap/commit/62dbb07af9dbb03acaa315e7ba8849bdef0c593a#r32019811).

**To Reproduce**
```
---
- name: Idempotence
  hosts: all
  gather_facts: false
  become: no
  vars:
    ansible_user: admin

  roles:
    - role: bootstrap
    - role: users
      vars:
        users:
          - name: admin
            comment: Ansible Management User
            uid: 2000
            cron: yes
            sudo: yes
            ssh_key:
              - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDVpUJQCOaPg3p5xro9e+1fkGRWNOGrrExiKMqTE91Fwu349bxfMnMzRS0PAERouR9EEL+Ee4Yzhav/uNc35eCtXzACtluXnAncMrQj6pM3IqASynhvXTygHljmcMbBSDQtLrTZeW+YzIcOgk5UM1yBi26WoUYva2aCr9IRvKdYreAK08OiMdZedpOye0ZdvIYJGcyITwc6YMmrAhP7jZlrk/mDEkf2a4eBp+475o7MJtaC9npqYkToM8vqvx5AGEKqXt7/f1/paOY7KsR+VGPQy6k2RkXjWBsXPesZ3d3XLZHE60wAk0EsuJO8A25+uWSB6ILQeRSYYmGea/WIf6kd noone@throwaway.example.com"
            generate_ssh_key: yes
```

**Expected behavior**
No connection errors. 

**Error**
Connection errors.

**Environment**
- Control node OS: [all]
- Control node Ansible version: [all]
- Managed node OS: [all]

**Additional context**
None.
