### ISSUE TITLE
Missing python-lxml package from CentOS systems

### ISSUE THREAD

**Issue by hwwilliams** [robertdebock/ansible-role-bootstrap#31]
**Describe the bug**
The role doesn't check for the python-lxml package which is required for the xml module.

**To Reproduce**
1. Run this role:
2. Attempt to run a task which uses the xml module
3. Error shows 'No module named lxml'

**Error**
![image](https://user-images.githubusercontent.com/20447447/62825607-c5c6f500-bb7c-11e9-9a96-23a72ebf66bb.png)

**Environment**
- Control node OS: CentOS 7
- Control node Ansible version: 2.8.2
- Managed node OS: CentOS 7

**Comment by robertdebock** [comment]
Thanks for the report, I'll verify a little later.

**Comment by robertdebock** [comment]
Hm, the module [xml](https://docs.ansible.com/ansible/latest/modules/xml_module.html) is a `community supported`, `preview module`, not a `stableinterface`, `core` module.

I'd like to keep this role as small as possible, I'm asking you to install `python-lxml` in some other role or task. Maybe like this:

```yaml
---
- name: Prepare
  hosts: all
  gather_facts: no
  become: yes

  roles:
    - robertdebock.bootstrap

  tasks:
    - name: install python-lxml
      package:
        name: python-lxml
        state: present
```

Hope this helps you.
