### ISSUE TITLE
This command has to be run under the root user

### ISSUE THREAD

**Issue by kennyth01** [robertdebock/ansible-role-bootstrap#39]
**Describe the bug**
Hello, I wanted to disable root login, and use another user named "ansible". This "ansible" user is a sudoer user and has all root privileges. The  "install bootstrap packages" require to be run under the root user? Is there any way I can bypass this because I don't want to use root?

**Playbook**

```yaml
- hosts: all
  #become: yes
  remote_user: ansible
  become_method: sudo
  gather_facts: no
  roles:
    - role: robertdebock.bootstrap
```

**Output**
TASK [robertdebock.bootstrap : install bootstrap packages]
failed: [xxx.xxx.xxx] (item=python3) => {"ansible_loop_var": "item", "attempts": 3, "changed": false, "item": "python3", "msg": "This command has to be run under the root user.", "results": []}

**Expected behavior**
Should install python if user got sudo privilege

**Environment**
- Control Node: MacOS
- Control Node Ansible Ver: Ansible 2.9.3
- Managed Node: CentOS 8

**Comment by kennyth01** [comment]
I added become and become_method and it seems it fixes the issue.
```yaml
  roles:
    - role: robertdebock.bootstrap
      become: yes
      become_method: sudo
```
