### ISSUE TITLE
"test if bootstrap_wait_for_host is set correctly" fails

### ISSUE THREAD

**Issue by quotengrote** [robertdebock/ansible-role-bootstrap#43]
## Description
The run fails because a conditionals check can't executed.
The bug was introduced in [005c7e0](https://github.com/robertdebock/ansible-role-bootstrap/commit/005c7e0ed4fc1dac9fef879e5b15fd388083797e)

```yaml
---
  - hosts: testeinzeln
    become: yes
    gather_facts: false
    max_fail_percentage: 20%

    roles:
      - { role: robertdebock.bootstrap, tags: "bootstrap" }
      - { role: ryandaniels.create_users, tags: "user", become: yes }
      - { role: nickjj.ansible-user, tag: "ansible", become: yes }

    vars:
      ### nickjj.ansible-users
      user_name: "ansible-user"
      user_local_ssh_key_path: "/home/mg/ansible/id_rsa_ansible_user_pub"
      user_enable_passwordless_sudo: True
      ### reobertdebock.bootstrap
      bootstrap_user: mg
      bootstrap_wait_for_host: no
      bootstrap_timeout: 1
      bootstrap_retries: 1
      ### ansible
      ansible_user: "mg"
      ansible_password: "XXXXXXXXXXXX"
      ansible_become_password: "XXXXXXXXXXXX"
      ansible_ssh_common_args: "'-o StrictHostKeyChecking=no'"

# Nach dem ersten durchlaufen ist keine Anmeldung mehr per Passwort & ssh möglich. Somit scheitert auch der Versuch das Playbook ein zweites mal durchlaufen zu lassen.

```
--> [Complete Repo](https://github.com/quotengrote/ansible)

## Output
```bash
mg@ansible:~/ansible$ ansible-playbook playbooks/base/1_bootstrap.yml -i inventories/inventory

PLAY [testeinzeln] **************************************************************************************************************************************************************************

TASK [robertdebock.bootstrap : include assert.yml] ******************************************************************************************************************************************
included: /home/mg/ansible/roles/robertdebock.bootstrap/tasks/assert.yml for vm-test.grote.lan

TASK [robertdebock.bootstrap : test if bootstrap_user is set correctly] *********************************************************************************************************************
ok: [vm-test.grote.lan]

TASK [robertdebock.bootstrap : test if bootstrap_wait_for_host is set correctly] ************************************************************************************************************
fatal: [vm-test.grote.lan]: FAILED! => {"msg": "The conditional check 'bootstrap_wait_for_host is boolean' failed. The error was: template error while templating string: no test named 'boolean'. String: {% if bootstrap_wait_for_host is boolean %} True {% else %} False {% endif %}"}

NO MORE HOSTS LEFT **************************************************************************************************************************************************************************

NO MORE HOSTS LEFT **************************************************************************************************************************************************************************

PLAY RECAP **********************************************************************************************************************************************************************************
vm-test.grote.lan          : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

## Environment

- Control node OS: 
```
mg@ansible:~/ansible$ uname -a
Linux ansible 5.4.65-1-pve #1 SMP PVE 5.4.65-1 (Mon, 21 Sep 2020 15:40:22 +0200) x86_64 x86_64 x86_64 GNU/Linux
mg@ansible:~/ansible$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
mg@ansible:~/ansible$ ansible --version
ansible 2.10.1
  config file = /home/mg/ansible/ansible.cfg
  configured module search path = ['/home/mg/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mg/.local/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]

```
- Managed node OS: 
```
mg@lxc-test:~/.ssh$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
