### ISSUE TITLE
running bootstrap against centos8 fails with "The conditional check 'bootstrap_wait_for_host is boolean' failed"

### ISSUE THREAD

**Issue by osmanburucu-ibm** [robertdebock/ansible-role-bootstrap#44]
## Describe the bug
Have used this role for a long time (last update was 6+ months before), did update today to latest version robertdebock.bootstrap, 4.3.6

## Playbook
my used playbook is simple:
YOUR PLAYBOOK HERE
```yaml
---
- name: bootstrap all hosts
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: robertdebock.bootstrap
      bootstrap_user: root
---
```

## Output
```sh
TASK [robertdebock.bootstrap : include assert.yml] ******************************************************************
included: /home/lnxadm/.ansible/roles/robertdebock.bootstrap/tasks/assert.yml for cos8e.local.net

TASK [robertdebock.bootstrap : test if bootstrap_user is set correctly] *********************************************
ok: [cos8e.local.net]

TASK [robertdebock.bootstrap : test if bootstrap_wait_for_host is set correctly] ************************************
fatal: [cos8e.local.net]: FAILED! => {"msg": "The conditional check 'bootstrap_wait_for_host is boolean' failed. The error was: template error while templating string: no test named 'boolean'. String: {% if bootstrap_wait_for_host is boolean %} True {% else %} False {% endif %}"}
```

Then i removed the offending lines from assert and main files:
```yaml
--- assert.yml
- name: test if bootstrap_wait_for_host is set correctly
  assert:
    that:
      - bootstrap_wait_for_host is defined
 #     - bootstrap_wait_for_host is boolean
    quiet: yes
---- mail.yml	
#- name: wait for host
#  wait_for:
#    port: "{{ ansible_port | default('22') }}"
#    host: "{{ (ansible_ssh_host | default(ansible_host) | default(inventory_hostname)) }}"
#  connection: local
#  become: no
#  when:
#    - ansible_connection is defined
#    - ansible_connection not in [ "docker", "container" ]
#    - bootstrap_wait_for_host | bool
```

it worked then...

## Environment

- Control node OS: [e.g. Debian 9] (`cat /etc/os-release`)
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

- Control node Ansible version: [e.g. 2.9.1] (`ansible --version`)
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/lnxadm/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
- Managed node OS: [e.g. CentOS 7] (`cat /etc/os-release`)

Please consider [sponsoring me](https://github.com/sponsors/robertdebock).
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
