### ISSUE TITLE
This role is incompatible with ansible 4.0.0

### ISSUE THREAD

**Issue by Tcharl** [robertdebock/ansible-role-bootstrap#48]
## Describe the bug

"msg": "The conditional check 'bootstrap_wait_for_host is boolean' failed. The error was: template error while templating string: no test named 'boolean'. String: {% if bootstrap_wait_for_host is boolean %} True {% else %} False {% endif %}"

In a role:
```yaml
- name: ansible-users | deps | import bootstrap role
  import_role:
    name: robertdebock.bootstrap
  become: True
```

## Output

See below, I can PR removing the checks, but I don't know if it's expected

## Environment

- Control node OS: your rdebock/fedora32 container
- See my [molecule tests](https://github.com/OsgiliathEnterprise/ansible-users/actions)
