### ISSUE TITLE
Modules lvol and lvg are not working

### ISSUE THREAD

**Issue by robertdebock** [robertdebock/ansible-role-bootstrap#6]
After running this role, it's not possible to use the (preview) modules lvol and/or lvg.

For CentOS the package `lvm2` is required.

To verify if this has been fixed, run these tasks.
```
- name: create volume group vg
  lvg:
    vg: vg
    pvs: /dev/sdb

- name: create logical volume
  lvol:
    vg: vg
    lv: lv
    size: 1024
```
